let suggestions = [
    "Auberto R. Urzal Jr. RID-B -00140350 Active Now",
    "Milbert T. Urzal RID-B -00140349 Active Now",
    "Marry Grace T. Urzal RID-B 00140348 Active Now",
    "Miguel Angelo B. Sabillo -RID-B-00140281 Active Now",
    "Wilson V. Sabillo RID-B -00140280 Active Now",
    "YouTube Channel",
    "Blogger",
    "Bollywood",
    "Vlogger",
    "Vechiles",
    "Facebook",
    "Freelancer",
    "Facebook Page",
    "Designer",
    "Developer",
    "Web Designer",
    "Web Developer",
    "Login Form in HTML & CSS",
    "How to learn HTML & CSS",
    "How to learn JavaScript",
    "How to become Freelancer",
    "How to become Web Designer",
    "How to start Gaming Channel",
    "How to start YouTube Channel",
    "What does HTML stands for?",
    "What does CSS stands for?",
];
